name: Build and Deployment

on:
  push:
    branches: [ "main" ]

env:
  NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - run: npm ci
        name: Install dependencies

      - run: npm test
        name: Run tests

  deploy:
    name: Deploy package
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - run: npm ci
        name: Install dependencies

      - run: npm run build
        name: Build package

      - name: Publish package
        run: "npm publish:pkg"
