name: Build and Deployment

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  test:
    name: Run tests (node ${{ matrix.node }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [18, 20, 22, 24]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - run: npm ci
        name: Install dependencies

      - run: npm test -- --coverage
        name: Run tests

      - run: npm run build
        name: Run build

      - run: npm run lint
        name: Check linting

      - run: npm run format:check
        name: Check formatting

      - run: npm run checkPkgTypes
        name: Check package type definitions

  deploy:
    name: Deploy package
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'
          always-auth: true
          registry-url: https://registry.npmjs.org
          scope: '@spearwolf'

      - run: npm ci
        name: Install dependencies

      - run: npm run build
        name: Build package

      - run: npm run publish:pkg
        name: Publish package
